language: node_js
jobs:
  include:
    - stage: test
      name: 'Unit Test'
      install: npm ci
      script: npm test
    - stage: test
      name: 'Lint'
      install: npm ci
      script: npm run lint
    - stage: test
      name: 'Coverage'
      install: npm ci
      script: npm run coveralls
    - stage: release
      if: branch = master
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        install: npm ci
        script: npx semantic-release
