language: js
node_js: 10
jobs:
  include:
    - stage: test
      name: 'Unit Test (8)'
      node_js: 8
      install: npm ci
      script: npm test
    - stage: test
      name: 'Unit Test (10)'
      node_js: 10
      install: npm ci
      script: npm test
    - stage: test
      name: 'Unit Test (12)'
      node_js: 12
      install: npm ci
      script: npm test
    - stage: test
      name: 'Lint'
      node_js: 10
      install: npm ci
      script: npm run lint
    - stage: test
      name: 'Coverage'
      node_js: 10
      install: npm ci
      script: npm run coveralls
    - stage: release
      if: branch = master
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
